# Generated by Django 5.1.6 on 2025-02-26 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(default='123 Main St, Anytown, USA', max_length=100),
        ),
    ]
