# Generated by Django 5.1.6 on 2025-02-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_donation_sponsor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
