# Generated by Django 5.1.6 on 2025-02-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_sponsor_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='business_name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
