# Generated by Django 5.1.6 on 2025-02-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_sponsor_business_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='business_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
