# Generated by Django 5.1.6 on 2025-03-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
    ]
